
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 04:55:31 KST (Jul  7 2026 19:55:31 UTC)

// Verification Directory fv/d_latch 

module d_latch(clk, i_d, o_q);
  input clk, i_d;
  output o_q;
  wire clk, i_d;
  wire o_q;
  wire UNCONNECTED;
  TLATX1 o_q_reg(.G (clk), .D (i_d), .Q (o_q), .QN (UNCONNECTED));
endmodule

