
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Aug 18 2026 03:44:18 KST (Aug 17 2026 18:44:18 UTC)

// Verification Directory fv/d_ff_ms_3 

module d_ff_ms_3(i_D, i_clk, o_Q);
  input i_D, i_clk;
  output o_Q;
  wire i_D, i_clk;
  wire o_Q;
  wire UNCONNECTED;
  DFFNSRX1 o_Q_reg(.RN (1'b1), .SN (1'b1), .CKN (i_clk), .D (i_D), .Q
       (o_Q), .QN (UNCONNECTED));
endmodule

