
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Aug 18 2026 03:56:45 KST (Aug 17 2026 18:56:45 UTC)

// Verification Directory fv/jk_ff_3 

module jk_ff_3(i_J, i_K, i_Clk, o_Q, o_NQ);
  input i_J, i_K, i_Clk;
  output o_Q, o_NQ;
  wire i_J, i_K, i_Clk;
  wire o_Q, o_NQ;
  wire n_0;
  SDFFQX1 o_Q_reg(.CK (i_Clk), .D (n_0), .SI (i_J), .SE (o_NQ), .Q
       (o_Q));
  INVXL g42(.A (o_Q), .Y (o_NQ));
  INVXL g41(.A (i_K), .Y (n_0));
endmodule

