
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  9 2026 04:48:00 KST (Jul  8 2026 19:48:00 UTC)

// Verification Directory fv/counter6_down 

module counter6_down(clk, rst_n, i_en, o_count);
  input clk, rst_n, i_en;
  output [2:0] o_count;
  wire clk, rst_n, i_en;
  wire [2:0] o_count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11;
  DFFHQX1 \o_count_reg[1] (.CK (clk), .D (n_11), .Q (o_count[1]));
  DFFHQX1 \o_count_reg[2] (.CK (clk), .D (n_10), .Q (o_count[2]));
  NOR2BX1 g113__2398(.AN (rst_n), .B (n_9), .Y (n_11));
  DFFHQX1 \o_count_reg[0] (.CK (clk), .D (n_7), .Q (o_count[0]));
  OAI221X1 g114__5107(.A0 (n_8), .A1 (n_4), .B0 (i_en), .B1 (n_5), .C0
       (rst_n), .Y (n_10));
  MX2XL g115__6260(.A (n_6), .B (n_0), .S0 (n_8), .Y (n_9));
  OAI221X1 g117__4319(.A0 (n_8), .A1 (n_2), .B0 (i_en), .B1 (n_1), .C0
       (rst_n), .Y (n_7));
  AOI32X1 g118__8428(.A0 (o_count[1]), .A1 (o_count[0]), .A2 (n_5), .B0
       (o_count[2]), .B1 (n_3), .Y (n_6));
  MXI2XL g119__5526(.A (o_count[2]), .B (n_5), .S0 (n_3), .Y (n_4));
  AOI21X1 g120__6783(.A0 (o_count[1]), .A1 (o_count[2]), .B0 (n_1), .Y
       (n_2));
  NOR2X1 g121__3680(.A (o_count[1]), .B (o_count[0]), .Y (n_3));
  INVXL g122(.A (o_count[1]), .Y (n_0));
  INVX1 g124(.A (o_count[0]), .Y (n_1));
  INVX1 g123(.A (o_count[2]), .Y (n_5));
  INVXL g125(.A (i_en), .Y (n_8));
endmodule

