
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Aug 18 2026 04:05:04 KST (Aug 17 2026 19:05:04 UTC)

// Verification Directory fv/t_ff_with_jk_3 

module t_ff_with_jk_3(i_T, i_Clk, o_Q, o_NQ);
  input i_T, i_Clk;
  output o_Q, o_NQ;
  wire i_T, i_Clk;
  wire o_Q, o_NQ;
  SDFFQX1 o_Q_reg(.CK (i_Clk), .D (o_Q), .SI (o_NQ), .SE (i_T), .Q
       (o_Q));
  INVXL g25(.A (o_Q), .Y (o_NQ));
endmodule

