
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 04:49:11 KST (Jul  7 2026 19:49:11 UTC)

// Verification Directory fv/bidirectional_bus_driver 

module bidirectional_bus_driver(i_data_to_bus, i_send, i_rcv,
     io_bus_data, o_data_from_bus);
  input [7:0] i_data_to_bus;
  input i_send, i_rcv;
  output [7:0] o_data_from_bus;
  inout [7:0] io_bus_data;
  wire [7:0] i_data_to_bus;
  wire i_send, i_rcv;
  wire [7:0] o_data_from_bus;
  wire [7:0] io_bus_data;
  AND2XL g77__2398(.A (i_rcv), .B (io_bus_data[5]), .Y
       (o_data_from_bus[5]));
  AND2XL g74__5107(.A (i_rcv), .B (io_bus_data[6]), .Y
       (o_data_from_bus[6]));
  AND2XL g75__6260(.A (i_rcv), .B (io_bus_data[7]), .Y
       (o_data_from_bus[7]));
  AND2XL g79__4319(.A (i_rcv), .B (io_bus_data[4]), .Y
       (o_data_from_bus[4]));
  AND2XL g76__8428(.A (i_rcv), .B (io_bus_data[1]), .Y
       (o_data_from_bus[1]));
  AND2XL g73__5526(.A (i_rcv), .B (io_bus_data[2]), .Y
       (o_data_from_bus[2]));
  AND2XL g80__6783(.A (i_rcv), .B (io_bus_data[3]), .Y
       (o_data_from_bus[3]));
  AND2XL g78__3680(.A (i_rcv), .B (io_bus_data[0]), .Y
       (o_data_from_bus[0]));
  TBUFX1 g1__1617(.A (i_data_to_bus[7]), .OE (i_send), .Y
       (io_bus_data[7]));
  TBUFX1 g11__2802(.A (i_data_to_bus[0]), .OE (i_send), .Y
       (io_bus_data[0]));
  TBUFX1 g6__1705(.A (i_data_to_bus[5]), .OE (i_send), .Y
       (io_bus_data[5]));
  TBUFX1 g5__5122(.A (i_data_to_bus[6]), .OE (i_send), .Y
       (io_bus_data[6]));
  TBUFX1 g10__8246(.A (i_data_to_bus[1]), .OE (i_send), .Y
       (io_bus_data[1]));
  TBUFX1 g8__7098(.A (i_data_to_bus[3]), .OE (i_send), .Y
       (io_bus_data[3]));
  TBUFX1 g9__6131(.A (i_data_to_bus[2]), .OE (i_send), .Y
       (io_bus_data[2]));
  TBUFX1 g7__1881(.A (i_data_to_bus[4]), .OE (i_send), .Y
       (io_bus_data[4]));
endmodule

