
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Aug 18 2026 04:56:39 KST (Aug 17 2026 19:56:39 UTC)

// Verification Directory fv/seq_tff_3 

module seq_tff_3(i_x, i_Clk, i_nRst, o_y);
  input i_x, i_Clk, i_nRst;
  output o_y;
  wire i_x, i_Clk, i_nRst;
  wire o_y;
  wire n_1, n_2, n_3, w_Ay, w_By;
  DFFRHQX1 w_Ay_reg(.RN (i_nRst), .CK (i_Clk), .D (n_3), .Q (w_Ay));
  DFFRHQX1 w_By_reg(.RN (i_nRst), .CK (i_Clk), .D (n_2), .Q (w_By));
  XNOR2X1 g90__2398(.A (n_1), .B (w_Ay), .Y (n_3));
  OA21X1 g92__5107(.A0 (i_x), .A1 (w_By), .B0 (n_1), .Y (n_2));
  NAND2XL g93__6260(.A (i_x), .B (w_By), .Y (n_1));
  AND2XL g94__4319(.A (w_By), .B (w_Ay), .Y (o_y));
endmodule

