
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 05:31:25 KST (Jul  7 2026 20:31:25 UTC)

// Verification Directory fv/FSM 

module FSM(clk, rst_n, din_bit, dout_bit);
  input clk, rst_n, din_bit;
  output dout_bit;
  wire clk, rst_n, din_bit;
  wire dout_bit;
  wire [2:0] state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_10;
  DFFRHQX1 \state_reg[2] (.RN (rst_n), .CK (clk), .D (n_10), .Q
       (state[2]));
  DFFRHQX1 \state_reg[1] (.RN (rst_n), .CK (clk), .D (n_7), .Q
       (state[1]));
  DFFRHQX1 \state_reg[0] (.RN (rst_n), .CK (clk), .D (n_6), .Q
       (state[0]));
  OAI31X1 g353__2398(.A0 (n_2), .A1 (state[2]), .A2 (n_1), .B0 (n_8),
       .Y (n_10));
  OAI31X1 g352__5107(.A0 (din_bit), .A1 (state[2]), .A2 (n_0), .B0
       (n_8), .Y (dout_bit));
  AOI2BB1X1 g354__6260(.A0N (state[0]), .A1N (n_3), .B0 (state[2]), .Y
       (n_7));
  AOI21X1 g355__4319(.A0 (state[2]), .A1 (n_5), .B0 (din_bit), .Y
       (n_6));
  NAND3X1 g356__8428(.A (din_bit), .B (state[2]), .C (n_4), .Y (n_8));
  INVX1 g357(.A (n_4), .Y (n_5));
  NOR2XL g358__5526(.A (n_2), .B (state[1]), .Y (n_3));
  NOR2X1 g359__6783(.A (state[1]), .B (state[0]), .Y (n_4));
  NAND2BX1 g360__3680(.AN (state[0]), .B (state[1]), .Y (n_1));
  NAND2XL g361__1617(.A (state[1]), .B (state[0]), .Y (n_0));
  INVXL g362(.A (din_bit), .Y (n_2));
endmodule

